### ISSUE TITLE
How to set language?!

### ISSUE THREAD

**Issue by johnkrmr** [Vidabe/cooking-units#21]
Hey, thank you for the fun and pretty handy package.
I would like to change the language from English to German. Switching the language is mentioned in the documentation a few times. Maybe it is to obvious, but I just can't find out how to do it.
Thank you in advance for any help.

**Comment by Vidabe** [comment]
I am glad you like the package :)

Changing the language is done via the commands provided by "babel" or "polyglossia" (depending on what you use). In my documentation, for example, I use babel and locally switch the language of my document to german via `\selectlanguage{ngerman}`. In a [minimum working example](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-working-example-mwe-what-is-that) it could look like this

```
\documentclass[ngerman]{scrartcl}
\usepackage[english,main=ngerman]{babel}
\usepackage{cooking-units}
\begin{document}
 
\selectlanguage{english} 
For this recipe we use \cutext{12}{kg} of flour and \dots

\selectlanguage{ngerman} 
In diesem Rezept verwenden wir \cutext{12}{kg} Mehl und \dots
 
\end{document}
```

For package "polyglossia" I think `\textlang` or something similar is used. Check the documentation if needed.

Currently there is no "cooking-units" option which allows you to change the language for the current command; although it might be interesting to have one.

Hope it helps.

**Comment by johnkrmr** [comment]
Yes, that really helped a lot. Thank you for the quick response!
